export const TEXT_ACTIONS = {
  SET_USERS: "SET_USERS",
  SET_LOADING_ERROR: "SET_LOADING_ERROR",
  SET_LOADING: "SET_LOADING",

  SET_CURRENT_USER: "SET_CURRENT_USER",
  SET_NAME: "SET_NAME",

  SET_FOLLOWERS: "SET_FOLLOWERS",
};
